[custom]

;设置规则标志位
ruleset=DIRECT,https://raw.githubusercontent.com/DeadAt17/rule/main/pccw_clash.yaml
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Teams/Teams.yaml
ruleset=哔哩哔哩,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml
ruleset=YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml
ruleset=Netflix,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml
ruleset=TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml
ruleset=AI节点,https://kelee.one/Tool/Clash/Rule/AI.yaml
ruleset=AI节点,https://raw.githubusercontent.com/DeadAt17/rule/main/ai_clash.yaml
ruleset=AI节点,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
ruleset=AI节点,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml
ruleset=AI节点,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BardAI/BardAI.yaml
ruleset=AI节点,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.yaml
ruleset=AI节点,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.yaml
ruleset=AI节点,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.yaml
ruleset=Apple,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt
ruleset=Apple,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt
ruleset=Delta,https://raw.githubusercontent.com/DeadAt17/rule/main/delta_clash.yaml
ruleset=Microsoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
ruleset=Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml
ruleset=节点选择,https://raw.githubusercontent.com/DeadAt17/rule/main/farms_clash.yaml
ruleset=节点选择,https://raw.githubusercontent.com/DeadAt17/rule/main/common_clash.yaml
ruleset=Telegram,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt
ruleset=节点选择,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
ruleset=节点选择,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
ruleset=节点选择,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt
ruleset=DIRECT,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt

;设置分组标志位
custom_proxy_group=节点选择`select`[]自动选择`[]香港节点`[]新加坡节点`[]日本节点`[]韩国节点`[]美国节点`[]台湾节点`.*
custom_proxy_group=自动选择`url-test`.*`http://www.YouTube.com/generate_204`200
custom_proxy_group=Telegram`select`[]自动选择`[]香港节点`[]新加坡节点`[]日本节点`[]韩国节点`[]美国节点`[]台湾节点
custom_proxy_group=哔哩哔哩`select`[]DIRECT`[]香港节点`[]台湾节点
custom_proxy_group=YouTube`select`[]自动选择`[]DIRECT`[]香港节点`[]日本节点`[]韩国节点`[]台湾节点`[]美国节点`[]新加坡节点
custom_proxy_group=Netflix`select`[]自动选择`[]DIRECT`[]香港节点`[]日本节点`[]韩国节点`[]台湾节点`[]美国节点`[]新加坡节点
custom_proxy_group=Apple`select`[]DIRECT`[]自动选择`[]香港节点`[]日本节点`[]韩国节点`[]台湾节点`[]美国节点`[]新加坡节点
custom_proxy_group=Delta`select`[]DIRECT`[]自动选择`[]香港节点`[]日本节点`[]韩国节点`[]台湾节点`[]美国节点`[]新加坡节点
custom_proxy_group=AI节点`select``gpt|GPT|chat|CHAT|chatgpt|ChatGPT`[]香港节点`[]日本节点`[]韩国节点`[]台湾节点`[]美国节点`[]新加坡节点
custom_proxy_group=TikTok`select`[]香港节点`[]日本节点`[]韩国节点`[]台湾节点`[]美国节点`[]新加坡节点
custom_proxy_group=Microsoft`select`[]DIRECT`[]自动选择`[]香港节点`[]日本节点`[]韩国节点`[]台湾节点`[]美国节点`[]新加坡节点
custom_proxy_group=Game`select`[]DIRECT`[]自动选择`[]香港节点`[]日本节点`[]韩国节点`[]台湾节点`[]美国节点`[]新加坡节点
custom_proxy_group=香港节点`url-test`香港|HK|中港|沪港|Hong`http://www.YouTube.com/generate_204`200
custom_proxy_group=台湾节点`url-test`台|新北|彰化|TW|Taiwan`http://www.YouTube.com/generate_204`200
custom_proxy_group=日本节点`url-test`日本((?!用).)+|东京|大阪|埼玉|JP|Japan`http://www.YouTube.com/generate_204`200
custom_proxy_group=韩国节点`url-test`KR|Korea|KOR|首尔|韩|韓|(?i)Korea`http://www.YouTube.com/generate_204`200
custom_proxy_group=美国节点`url-test`美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|California|芝加哥|United States|US`http://www.YouTube.com/generate_204`200
custom_proxy_group=新加坡节点`url-test`SG|sg|加坡|狮城|Singapore`http://www.YouTube.com/generate_204`200

enable_rule_generator=true
overwrite_original_rules=true
